orbs:
  nexus-orb: sonatype/nexus-platform-orb@1.0.2


version: 2.1 # use CircleCI 2.1
jobs:
  build:
    
    working_directory: ~/circleci-demo-java-spring

    docker:
      - image: circleci/openjdk:8-jdk-browsers
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    steps:

      - checkout

      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      
      - run: mvn package -DskipTests -DskipITs
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/demo-java-spring-0.0.1-RELEASE.jar

      - run: curl -v -u "${NEXUS_RM_USERNAME}":"${NEXUS_RM_PASSWORD}" --upload-file target/demo-java-spring-0.0.1-RELEASE.jar https://jenkins-linode.3ap.ch/nexus/repository/testRepo/ch.aaap/config-server/0.0.4/config-server-0.0.4-RELEASE.jar

#
#      - nexus-orb/install
#
#      - nexus-orb/publish:
#          filename: "target/demo-java-spring-0.0.1-RELEASE.jar"
#          attributes: "-CgroupId=org -CartifactId=foo -Cversion=1.0 -Aextension=jar"
#          username: "jenkins"
#          password: "qqNr3sc5"
#          serverurl: "https://jenkins-linode.3ap.ch/nexus/repository/testRepo/"
